version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - TZ=Asia/Jakarta
      - PORT=8000
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/pangan-db
    volumes:
      - ./:/app

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pangan-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pangan-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:


